/**
 * STATIC UNIVERSE — replaces EODHD exchange-symbol-list
 *
 * Sources (June 2026):
 *   US:    S&P 500 constituents (github.com/datasets/s-and-p-500-companies)
 *   XETRA: DAX 40
 *   PA:    CAC 40
 *   AS:    AEX 25
 *   BR:    BEL 20
 *   LS:    PSI 20
 *   MI:    FTSE MIB 40
 *   SW:    SMI 20
 *   LSE:   FTSE 100
 *
 * Update: quarterly or when major index reconstitution occurs.
 * Last updated: 2026-06
 */

export const STATIC_UNIVERSE_VERSION = "2026-Q2";

// Format per asset: { Code, Name, Type, Exchange, Currency }
// Exchange must match the allowedExchanges in universeEngine.js PROVIDER_EXCHANGES

const US = [
  { Code: "MMM",  Name: "3M",                        Exchange: "NYSE",   Currency: "USD" },
  { Code: "AOS",  Name: "A. O. Smith",                Exchange: "NYSE",   Currency: "USD" },
  { Code: "ABT",  Name: "Abbott Laboratories",        Exchange: "NYSE",   Currency: "USD" },
  { Code: "ABBV", Name: "AbbVie",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "ACN",  Name: "Accenture",                  Exchange: "NYSE",   Currency: "USD" },
  { Code: "ADBE", Name: "Adobe Inc.",                 Exchange: "NASDAQ", Currency: "USD" },
  { Code: "AMD",  Name: "Advanced Micro Devices",     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "AFL",  Name: "Aflac",                      Exchange: "NYSE",   Currency: "USD" },
  { Code: "APD",  Name: "Air Products",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "AKAM", Name: "Akamai Technologies",        Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ALB",  Name: "Albemarle",                  Exchange: "NYSE",   Currency: "USD" },
  { Code: "ALGN", Name: "Align Technology",           Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ALLE", Name: "Allegion",                   Exchange: "NYSE",   Currency: "USD" },
  { Code: "LNT",  Name: "Alliant Energy",             Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ALL",  Name: "Allstate",                   Exchange: "NYSE",   Currency: "USD" },
  { Code: "GOOGL",Name: "Alphabet Inc. Class A",      Exchange: "NASDAQ", Currency: "USD" },
  { Code: "GOOG", Name: "Alphabet Inc. Class C",      Exchange: "NASDAQ", Currency: "USD" },
  { Code: "MO",   Name: "Altria",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "AMZN", Name: "Amazon",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "AMCR", Name: "Amcor",                      Exchange: "NYSE",   Currency: "USD" },
  { Code: "AEE",  Name: "Ameren",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "AEP",  Name: "American Electric Power",    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "AXP",  Name: "American Express",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "AIG",  Name: "American International Group",Exchange:"NYSE",   Currency: "USD" },
  { Code: "AMT",  Name: "American Tower",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "AWK",  Name: "American Water Works",       Exchange: "NYSE",   Currency: "USD" },
  { Code: "AMP",  Name: "Ameriprise Financial",       Exchange: "NYSE",   Currency: "USD" },
  { Code: "AME",  Name: "Ametek",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "AMGN", Name: "Amgen",                      Exchange: "NASDAQ", Currency: "USD" },
  { Code: "APH",  Name: "Amphenol",                   Exchange: "NYSE",   Currency: "USD" },
  { Code: "ADI",  Name: "Analog Devices",             Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ANET", Name: "Arista Networks",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "T",    Name: "AT&T",                       Exchange: "NYSE",   Currency: "USD" },
  { Code: "ADSK", Name: "Autodesk",                   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ADP",  Name: "Automatic Data Processing",  Exchange: "NASDAQ", Currency: "USD" },
  { Code: "AZO",  Name: "AutoZone",                   Exchange: "NYSE",   Currency: "USD" },
  { Code: "AVB",  Name: "AvalonBay Communities",      Exchange: "NYSE",   Currency: "USD" },
  { Code: "AXON", Name: "Axon Enterprise",            Exchange: "NASDAQ", Currency: "USD" },
  { Code: "BKR",  Name: "Baker Hughes",               Exchange: "NASDAQ", Currency: "USD" },
  { Code: "BALL", Name: "Ball Corporation",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "BAC",  Name: "Bank of America",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "BAX",  Name: "Baxter International",       Exchange: "NYSE",   Currency: "USD" },
  { Code: "BDX",  Name: "Becton Dickinson",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "BBY",  Name: "Best Buy",                   Exchange: "NYSE",   Currency: "USD" },
  { Code: "BIIB", Name: "Biogen",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "BLK",  Name: "BlackRock",                  Exchange: "NYSE",   Currency: "USD" },
  { Code: "BX",   Name: "Blackstone",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "BA",   Name: "Boeing",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "BKNG", Name: "Booking Holdings",           Exchange: "NASDAQ", Currency: "USD" },
  { Code: "BSX",  Name: "Boston Scientific",          Exchange: "NYSE",   Currency: "USD" },
  { Code: "BMY",  Name: "Bristol Myers Squibb",       Exchange: "NYSE",   Currency: "USD" },
  { Code: "AVGO", Name: "Broadcom",                   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "BR",   Name: "Broadridge Financial",       Exchange: "NYSE",   Currency: "USD" },
  { Code: "CDNS", Name: "Cadence Design Systems",     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "COF",  Name: "Capital One",                Exchange: "NYSE",   Currency: "USD" },
  { Code: "CAH",  Name: "Cardinal Health",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "CARR", Name: "Carrier Global",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "CAT",  Name: "Caterpillar",                Exchange: "NYSE",   Currency: "USD" },
  { Code: "CBOE", Name: "Cboe Global Markets",        Exchange: "NASDAQ", Currency: "USD" },
  { Code: "CBRE", Name: "CBRE Group",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "CVX",  Name: "Chevron",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "CMG",  Name: "Chipotle Mexican Grill",     Exchange: "NYSE",   Currency: "USD" },
  { Code: "CB",   Name: "Chubb Limited",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "CI",   Name: "Cigna",                      Exchange: "NYSE",   Currency: "USD" },
  { Code: "CTAS", Name: "Cintas",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "CSCO", Name: "Cisco",                      Exchange: "NASDAQ", Currency: "USD" },
  { Code: "C",    Name: "Citigroup",                  Exchange: "NYSE",   Currency: "USD" },
  { Code: "CLX",  Name: "Clorox",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "CME",  Name: "CME Group",                  Exchange: "NASDAQ", Currency: "USD" },
  { Code: "KO",   Name: "Coca-Cola",                  Exchange: "NYSE",   Currency: "USD" },
  { Code: "CTSH", Name: "Cognizant",                  Exchange: "NASDAQ", Currency: "USD" },
  { Code: "CL",   Name: "Colgate-Palmolive",          Exchange: "NYSE",   Currency: "USD" },
  { Code: "CMCSA",Name: "Comcast",                    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "COP",  Name: "ConocoPhillips",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "ED",   Name: "Consolidated Edison",        Exchange: "NYSE",   Currency: "USD" },
  { Code: "CEG",  Name: "Constellation Energy",       Exchange: "NASDAQ", Currency: "USD" },
  { Code: "COST", Name: "Costco",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "CRH",  Name: "CRH plc",                   Exchange: "NYSE",   Currency: "USD" },
  { Code: "CRWD", Name: "CrowdStrike",                Exchange: "NASDAQ", Currency: "USD" },
  { Code: "CSX",  Name: "CSX Corporation",            Exchange: "NASDAQ", Currency: "USD" },
  { Code: "CMI",  Name: "Cummins",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "CVS",  Name: "CVS Health",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "DHR",  Name: "Danaher",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "DDOG", Name: "Datadog",                    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "DE",   Name: "Deere & Company",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "DELL", Name: "Dell Technologies",          Exchange: "NYSE",   Currency: "USD" },
  { Code: "DAL",  Name: "Delta Air Lines",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "DVN",  Name: "Devon Energy",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "DXCM", Name: "Dexcom",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "FANG", Name: "Diamondback Energy",         Exchange: "NASDAQ", Currency: "USD" },
  { Code: "DLR",  Name: "Digital Realty",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "DG",   Name: "Dollar General",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "DLTR", Name: "Dollar Tree",                Exchange: "NASDAQ", Currency: "USD" },
  { Code: "D",    Name: "Dominion Energy",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "DPZ",  Name: "Domino's",                   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "DASH", Name: "DoorDash",                   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "DOV",  Name: "Dover Corporation",          Exchange: "NYSE",   Currency: "USD" },
  { Code: "DOW",  Name: "Dow Inc.",                   Exchange: "NYSE",   Currency: "USD" },
  { Code: "DHI",  Name: "D. R. Horton",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "DTE",  Name: "DTE Energy",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "DUK",  Name: "Duke Energy",                Exchange: "NYSE",   Currency: "USD" },
  { Code: "DD",   Name: "DuPont",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "ETN",  Name: "Eaton Corporation",          Exchange: "NYSE",   Currency: "USD" },
  { Code: "EBAY", Name: "eBay",                       Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ECL",  Name: "Ecolab",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "EIX",  Name: "Edison International",       Exchange: "NYSE",   Currency: "USD" },
  { Code: "EW",   Name: "Edwards Lifesciences",       Exchange: "NYSE",   Currency: "USD" },
  { Code: "EA",   Name: "Electronic Arts",            Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ELV",  Name: "Elevance Health",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "EMR",  Name: "Emerson Electric",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "ETR",  Name: "Entergy",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "EOG",  Name: "EOG Resources",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "EFX",  Name: "Equifax",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "EQIX", Name: "Equinix",                    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "EQR",  Name: "Equity Residential",         Exchange: "NYSE",   Currency: "USD" },
  { Code: "ESS",  Name: "Essex Property Trust",       Exchange: "NYSE",   Currency: "USD" },
  { Code: "EL",   Name: "Estée Lauder",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "EXC",  Name: "Exelon",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "EXPD", Name: "Expeditors International",   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "EXPE", Name: "Expedia",                    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "EXR",  Name: "Extra Space Storage",        Exchange: "NYSE",   Currency: "USD" },
  { Code: "XOM",  Name: "ExxonMobil",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "FFIV", Name: "F5 Inc.",                    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "FDS",  Name: "FactSet",                    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "FICO", Name: "Fair Isaac",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "FAST", Name: "Fastenal",                   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "FDX",  Name: "FedEx",                      Exchange: "NYSE",   Currency: "USD" },
  { Code: "FIS",  Name: "Fidelity National Info Svcs",Exchange: "NYSE",   Currency: "USD" },
  { Code: "FITB", Name: "Fifth Third Bancorp",        Exchange: "NASDAQ", Currency: "USD" },
  { Code: "FSLR", Name: "First Solar",               Exchange: "NASDAQ", Currency: "USD" },
  { Code: "FE",   Name: "FirstEnergy",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "FISV", Name: "Fiserv",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "F",    Name: "Ford Motor",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "FTNT", Name: "Fortinet",                   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "FCX",  Name: "Freeport-McMoRan",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "GRMN", Name: "Garmin",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "IT",   Name: "Gartner",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "GE",   Name: "GE Aerospace",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "GEHC", Name: "GE HealthCare",              Exchange: "NASDAQ", Currency: "USD" },
  { Code: "GEV",  Name: "GE Vernova",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "GD",   Name: "General Dynamics",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "GIS",  Name: "General Mills",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "GM",   Name: "General Motors",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "GPC",  Name: "Genuine Parts",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "GILD", Name: "Gilead Sciences",            Exchange: "NASDAQ", Currency: "USD" },
  { Code: "GPN",  Name: "Global Payments",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "GS",   Name: "Goldman Sachs",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "HAL",  Name: "Halliburton",                Exchange: "NYSE",   Currency: "USD" },
  { Code: "HCA",  Name: "HCA Healthcare",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "HSY",  Name: "Hershey",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "HPE",  Name: "Hewlett Packard Enterprise", Exchange: "NYSE",   Currency: "USD" },
  { Code: "HLT",  Name: "Hilton Worldwide",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "HD",   Name: "Home Depot",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "HON",  Name: "Honeywell",                  Exchange: "NASDAQ", Currency: "USD" },
  { Code: "HRL",  Name: "Hormel Foods",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "HWM",  Name: "Howmet Aerospace",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "HPQ",  Name: "HP Inc.",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "HUM",  Name: "Humana",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "IBM",  Name: "IBM",                        Exchange: "NYSE",   Currency: "USD" },
  { Code: "IDXX", Name: "Idexx Laboratories",         Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ITW",  Name: "Illinois Tool Works",        Exchange: "NYSE",   Currency: "USD" },
  { Code: "INCY", Name: "Incyte",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "IR",   Name: "Ingersoll Rand",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "INTC", Name: "Intel",                      Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ICE",  Name: "Intercontinental Exchange",  Exchange: "NYSE",   Currency: "USD" },
  { Code: "IFF",  Name: "Intl Flavors & Fragrances",  Exchange: "NYSE",   Currency: "USD" },
  { Code: "INTU", Name: "Intuit",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ISRG", Name: "Intuitive Surgical",         Exchange: "NASDAQ", Currency: "USD" },
  { Code: "IQV",  Name: "IQVIA",                      Exchange: "NYSE",   Currency: "USD" },
  { Code: "JNJ",  Name: "Johnson & Johnson",          Exchange: "NYSE",   Currency: "USD" },
  { Code: "JCI",  Name: "Johnson Controls",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "JPM",  Name: "JPMorgan Chase",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "KEYS", Name: "Keysight Technologies",      Exchange: "NYSE",   Currency: "USD" },
  { Code: "KMB",  Name: "Kimberly-Clark",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "KIM",  Name: "Kimco Realty",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "KMI",  Name: "Kinder Morgan",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "KKR",  Name: "KKR & Co.",                  Exchange: "NYSE",   Currency: "USD" },
  { Code: "KLAC", Name: "KLA Corporation",            Exchange: "NASDAQ", Currency: "USD" },
  { Code: "KR",   Name: "Kroger",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "LHX",  Name: "L3Harris",                   Exchange: "NYSE",   Currency: "USD" },
  { Code: "LRCX", Name: "Lam Research",               Exchange: "NASDAQ", Currency: "USD" },
  { Code: "LVS",  Name: "Las Vegas Sands",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "LDOS", Name: "Leidos",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "LEN",  Name: "Lennar",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "LLY",  Name: "Lilly (Eli)",                Exchange: "NYSE",   Currency: "USD" },
  { Code: "LIN",  Name: "Linde plc",                  Exchange: "NASDAQ", Currency: "USD" },
  { Code: "LMT",  Name: "Lockheed Martin",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "LOW",  Name: "Lowe's",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "LULU", Name: "Lululemon Athletica",        Exchange: "NASDAQ", Currency: "USD" },
  { Code: "MPC",  Name: "Marathon Petroleum",         Exchange: "NYSE",   Currency: "USD" },
  { Code: "MAR",  Name: "Marriott International",     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "MLM",  Name: "Martin Marietta Materials",  Exchange: "NYSE",   Currency: "USD" },
  { Code: "MA",   Name: "Mastercard",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "MCD",  Name: "McDonald's",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "MCK",  Name: "McKesson",                   Exchange: "NYSE",   Currency: "USD" },
  { Code: "MDT",  Name: "Medtronic",                  Exchange: "NYSE",   Currency: "USD" },
  { Code: "MRK",  Name: "Merck & Co.",                Exchange: "NYSE",   Currency: "USD" },
  { Code: "META", Name: "Meta Platforms",             Exchange: "NASDAQ", Currency: "USD" },
  { Code: "MET",  Name: "MetLife",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "MCHP", Name: "Microchip Technology",       Exchange: "NASDAQ", Currency: "USD" },
  { Code: "MU",   Name: "Micron Technology",          Exchange: "NASDAQ", Currency: "USD" },
  { Code: "MSFT", Name: "Microsoft",                  Exchange: "NASDAQ", Currency: "USD" },
  { Code: "MRNA", Name: "Moderna",                    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "MDLZ", Name: "Mondelez International",     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "MPWR", Name: "Monolithic Power Systems",   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "MNST", Name: "Monster Beverage",           Exchange: "NASDAQ", Currency: "USD" },
  { Code: "MCO",  Name: "Moody's",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "MS",   Name: "Morgan Stanley",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "MSI",  Name: "Motorola Solutions",         Exchange: "NYSE",   Currency: "USD" },
  { Code: "MSCI", Name: "MSCI Inc.",                  Exchange: "NYSE",   Currency: "USD" },
  { Code: "NDAQ", Name: "Nasdaq Inc.",                Exchange: "NASDAQ", Currency: "USD" },
  { Code: "NTAP", Name: "NetApp",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "NFLX", Name: "Netflix",                    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "NEM",  Name: "Newmont",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "NEE",  Name: "NextEra Energy",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "NKE",  Name: "Nike",                       Exchange: "NYSE",   Currency: "USD" },
  { Code: "NSC",  Name: "Norfolk Southern",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "NOC",  Name: "Northrop Grumman",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "NVDA", Name: "Nvidia",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "NXPI", Name: "NXP Semiconductors",        Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ORLY", Name: "O'Reilly Automotive",        Exchange: "NASDAQ", Currency: "USD" },
  { Code: "OXY",  Name: "Occidental Petroleum",       Exchange: "NYSE",   Currency: "USD" },
  { Code: "ODFL", Name: "Old Dominion Freight",       Exchange: "NASDAQ", Currency: "USD" },
  { Code: "OMC",  Name: "Omnicom Group",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "ON",   Name: "ON Semiconductor",           Exchange: "NASDAQ", Currency: "USD" },
  { Code: "OKE",  Name: "Oneok",                      Exchange: "NYSE",   Currency: "USD" },
  { Code: "ORCL", Name: "Oracle",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "OTIS", Name: "Otis Worldwide",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "PCAR", Name: "Paccar",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "PLTR", Name: "Palantir Technologies",      Exchange: "NASDAQ", Currency: "USD" },
  { Code: "PANW", Name: "Palo Alto Networks",         Exchange: "NASDAQ", Currency: "USD" },
  { Code: "PH",   Name: "Parker Hannifin",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "PAYX", Name: "Paychex",                    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "PYPL", Name: "PayPal",                     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "PEP",  Name: "PepsiCo",                    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "PFE",  Name: "Pfizer",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "PCG",  Name: "PG&E Corporation",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "PM",   Name: "Philip Morris",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "PSX",  Name: "Phillips 66",                Exchange: "NYSE",   Currency: "USD" },
  { Code: "PNC",  Name: "PNC Financial",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "POOL", Name: "Pool Corporation",           Exchange: "NASDAQ", Currency: "USD" },
  { Code: "PPG",  Name: "PPG Industries",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "PPL",  Name: "PPL Corporation",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "PG",   Name: "Procter & Gamble",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "PGR",  Name: "Progressive Corporation",    Exchange: "NYSE",   Currency: "USD" },
  { Code: "PLD",  Name: "Prologis",                   Exchange: "NYSE",   Currency: "USD" },
  { Code: "PRU",  Name: "Prudential Financial",       Exchange: "NYSE",   Currency: "USD" },
  { Code: "PTC",  Name: "PTC Inc.",                   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "PSA",  Name: "Public Storage",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "PHM",  Name: "PulteGroup",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "PWR",  Name: "Quanta Services",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "QCOM", Name: "Qualcomm",                   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "RL",   Name: "Ralph Lauren",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "RTX",  Name: "RTX Corporation",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "O",    Name: "Realty Income",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "REGN", Name: "Regeneron",                  Exchange: "NASDAQ", Currency: "USD" },
  { Code: "RF",   Name: "Regions Financial",          Exchange: "NYSE",   Currency: "USD" },
  { Code: "RSG",  Name: "Republic Services",          Exchange: "NYSE",   Currency: "USD" },
  { Code: "RMD",  Name: "ResMed",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "ROK",  Name: "Rockwell Automation",        Exchange: "NYSE",   Currency: "USD" },
  { Code: "ROP",  Name: "Roper Technologies",         Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ROST", Name: "Ross Stores",                Exchange: "NASDAQ", Currency: "USD" },
  { Code: "RCL",  Name: "Royal Caribbean",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "SPGI", Name: "S&P Global",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "CRM",  Name: "Salesforce",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "SBAC", Name: "SBA Communications",         Exchange: "NASDAQ", Currency: "USD" },
  { Code: "SLB",  Name: "Schlumberger",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "SRE",  Name: "Sempra",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "NOW",  Name: "ServiceNow",                 Exchange: "NYSE",   Currency: "USD" },
  { Code: "SHW",  Name: "Sherwin-Williams",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "SPG",  Name: "Simon Property Group",       Exchange: "NYSE",   Currency: "USD" },
  { Code: "SWKS", Name: "Skyworks Solutions",         Exchange: "NASDAQ", Currency: "USD" },
  { Code: "SNA",  Name: "Snap-on",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "SO",   Name: "Southern Company",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "SWK",  Name: "Stanley Black & Decker",     Exchange: "NYSE",   Currency: "USD" },
  { Code: "SBUX", Name: "Starbucks",                  Exchange: "NASDAQ", Currency: "USD" },
  { Code: "STT",  Name: "State Street",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "STLD", Name: "Steel Dynamics",             Exchange: "NASDAQ", Currency: "USD" },
  { Code: "STE",  Name: "Steris",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "SYK",  Name: "Stryker",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "SYF",  Name: "Synchrony Financial",        Exchange: "NYSE",   Currency: "USD" },
  { Code: "SNPS", Name: "Synopsys",                   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "SYY",  Name: "Sysco",                      Exchange: "NYSE",   Currency: "USD" },
  { Code: "TMUS", Name: "T-Mobile US",                Exchange: "NASDAQ", Currency: "USD" },
  { Code: "TROW", Name: "T. Rowe Price",              Exchange: "NASDAQ", Currency: "USD" },
  { Code: "TGT",  Name: "Target",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "TEL",  Name: "TE Connectivity",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "TSLA", Name: "Tesla",                      Exchange: "NASDAQ", Currency: "USD" },
  { Code: "TXN",  Name: "Texas Instruments",          Exchange: "NASDAQ", Currency: "USD" },
  { Code: "TXT",  Name: "Textron",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "TMO",  Name: "Thermo Fisher Scientific",   Exchange: "NYSE",   Currency: "USD" },
  { Code: "TJX",  Name: "TJX Companies",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "TSCO", Name: "Tractor Supply",             Exchange: "NASDAQ", Currency: "USD" },
  { Code: "TT",   Name: "Trane Technologies",         Exchange: "NYSE",   Currency: "USD" },
  { Code: "TDG",  Name: "TransDigm Group",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "TRV",  Name: "Travelers",                  Exchange: "NYSE",   Currency: "USD" },
  { Code: "TTD",  Name: "Trade Desk",                 Exchange: "NASDAQ", Currency: "USD" },
  { Code: "TFC",  Name: "Truist Financial",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "USB",  Name: "U.S. Bancorp",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "UBER", Name: "Uber",                       Exchange: "NYSE",   Currency: "USD" },
  { Code: "UNP",  Name: "Union Pacific",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "UAL",  Name: "United Airlines",            Exchange: "NASDAQ", Currency: "USD" },
  { Code: "UPS",  Name: "United Parcel Service",      Exchange: "NYSE",   Currency: "USD" },
  { Code: "URI",  Name: "United Rentals",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "UNH",  Name: "UnitedHealth Group",         Exchange: "NYSE",   Currency: "USD" },
  { Code: "VLO",  Name: "Valero Energy",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "VEEV", Name: "Veeva Systems",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "VRSN", Name: "Verisign",                   Exchange: "NASDAQ", Currency: "USD" },
  { Code: "VRSK", Name: "Verisk Analytics",           Exchange: "NASDAQ", Currency: "USD" },
  { Code: "VZ",   Name: "Verizon",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "VRTX", Name: "Vertex Pharmaceuticals",     Exchange: "NASDAQ", Currency: "USD" },
  { Code: "VRT",  Name: "Vertiv",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "VICI", Name: "Vici Properties",            Exchange: "NYSE",   Currency: "USD" },
  { Code: "V",    Name: "Visa",                       Exchange: "NYSE",   Currency: "USD" },
  { Code: "VST",  Name: "Vistra Corp.",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "VMC",  Name: "Vulcan Materials",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "GWW",  Name: "W. W. Grainger",             Exchange: "NYSE",   Currency: "USD" },
  { Code: "WAB",  Name: "Wabtec",                     Exchange: "NYSE",   Currency: "USD" },
  { Code: "WMT",  Name: "Walmart",                    Exchange: "NYSE",   Currency: "USD" },
  { Code: "DIS",  Name: "Walt Disney",                Exchange: "NYSE",   Currency: "USD" },
  { Code: "WM",   Name: "Waste Management",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "WAT",  Name: "Waters Corporation",         Exchange: "NYSE",   Currency: "USD" },
  { Code: "WEC",  Name: "WEC Energy Group",           Exchange: "NYSE",   Currency: "USD" },
  { Code: "WFC",  Name: "Wells Fargo",                Exchange: "NYSE",   Currency: "USD" },
  { Code: "WELL", Name: "Welltower",                  Exchange: "NYSE",   Currency: "USD" },
  { Code: "WDC",  Name: "Western Digital",            Exchange: "NASDAQ", Currency: "USD" },
  { Code: "WY",   Name: "Weyerhaeuser",               Exchange: "NYSE",   Currency: "USD" },
  { Code: "WMB",  Name: "Williams Companies",         Exchange: "NYSE",   Currency: "USD" },
  { Code: "WDAY", Name: "Workday",                    Exchange: "NASDAQ", Currency: "USD" },
  { Code: "XEL",  Name: "Xcel Energy",               Exchange: "NASDAQ", Currency: "USD" },
  { Code: "XYL",  Name: "Xylem",                      Exchange: "NYSE",   Currency: "USD" },
  { Code: "YUM",  Name: "Yum! Brands",                Exchange: "NYSE",   Currency: "USD" },
  { Code: "ZBRA", Name: "Zebra Technologies",         Exchange: "NASDAQ", Currency: "USD" },
  { Code: "ZBH",  Name: "Zimmer Biomet",              Exchange: "NYSE",   Currency: "USD" },
  { Code: "ZTS",  Name: "Zoetis",                     Exchange: "NYSE",   Currency: "USD" },
];

const XETRA = [
  { Code: "ADS",  Name: "Adidas",                     Exchange: "XETRA", Currency: "EUR" },
  { Code: "AIR",  Name: "Airbus",                     Exchange: "XETRA", Currency: "EUR" },
  { Code: "ALV",  Name: "Allianz",                    Exchange: "XETRA", Currency: "EUR" },
  { Code: "BAS",  Name: "BASF",                       Exchange: "XETRA", Currency: "EUR" },
  { Code: "BAYN", Name: "Bayer",                      Exchange: "XETRA", Currency: "EUR" },
  { Code: "BEI",  Name: "Beiersdorf",                 Exchange: "XETRA", Currency: "EUR" },
  { Code: "BMW",  Name: "BMW",                        Exchange: "XETRA", Currency: "EUR" },
  { Code: "BNR",  Name: "Brenntag",                   Exchange: "XETRA", Currency: "EUR" },
  { Code: "CBK",  Name: "Commerzbank",                Exchange: "XETRA", Currency: "EUR" },
  { Code: "CON",  Name: "Continental",                Exchange: "XETRA", Currency: "EUR" },
  { Code: "DTG",  Name: "Daimler Truck",              Exchange: "XETRA", Currency: "EUR" },
  { Code: "DBK",  Name: "Deutsche Bank",              Exchange: "XETRA", Currency: "EUR" },
  { Code: "DB1",  Name: "Deutsche Boerse",            Exchange: "XETRA", Currency: "EUR" },
  { Code: "DHL",  Name: "Deutsche Post",              Exchange: "XETRA", Currency: "EUR" },
  { Code: "DTE",  Name: "Deutsche Telekom",           Exchange: "XETRA", Currency: "EUR" },
  { Code: "EOAN", Name: "E.ON",                       Exchange: "XETRA", Currency: "EUR" },
  { Code: "FRE",  Name: "Fresenius",                  Exchange: "XETRA", Currency: "EUR" },
  { Code: "FME",  Name: "Fresenius Medical Care",     Exchange: "XETRA", Currency: "EUR" },
  { Code: "G1A",  Name: "GEA Group",                  Exchange: "XETRA", Currency: "EUR" },
  { Code: "HNR1", Name: "Hannover Re",                Exchange: "XETRA", Currency: "EUR" },
  { Code: "HEI",  Name: "Heidelberg Materials",       Exchange: "XETRA", Currency: "EUR" },
  { Code: "HEN3", Name: "Henkel",                     Exchange: "XETRA", Currency: "EUR" },
  { Code: "IFX",  Name: "Infineon Technologies",      Exchange: "XETRA", Currency: "EUR" },
  { Code: "MBG",  Name: "Mercedes-Benz Group",        Exchange: "XETRA", Currency: "EUR" },
  { Code: "MRK",  Name: "Merck KGaA",                 Exchange: "XETRA", Currency: "EUR" },
  { Code: "MTX",  Name: "MTU Aero Engines",           Exchange: "XETRA", Currency: "EUR" },
  { Code: "MUV2", Name: "Munich Re",                  Exchange: "XETRA", Currency: "EUR" },
  { Code: "PAH3", Name: "Porsche SE",                 Exchange: "XETRA", Currency: "EUR" },
  { Code: "QIA",  Name: "Qiagen",                     Exchange: "XETRA", Currency: "EUR" },
  { Code: "RHM",  Name: "Rheinmetall",                Exchange: "XETRA", Currency: "EUR" },
  { Code: "RWE",  Name: "RWE",                        Exchange: "XETRA", Currency: "EUR" },
  { Code: "SAP",  Name: "SAP",                        Exchange: "XETRA", Currency: "EUR" },
  { Code: "G24",  Name: "Scout24",                    Exchange: "XETRA", Currency: "EUR" },
  { Code: "SIE",  Name: "Siemens",                    Exchange: "XETRA", Currency: "EUR" },
  { Code: "ENR",  Name: "Siemens Energy",             Exchange: "XETRA", Currency: "EUR" },
  { Code: "SHL",  Name: "Siemens Healthineers",       Exchange: "XETRA", Currency: "EUR" },
  { Code: "SY1",  Name: "Symrise",                    Exchange: "XETRA", Currency: "EUR" },
  { Code: "VOW3", Name: "Volkswagen",                 Exchange: "XETRA", Currency: "EUR" },
  { Code: "VNA",  Name: "Vonovia",                    Exchange: "XETRA", Currency: "EUR" },
  { Code: "ZAL",  Name: "Zalando",                    Exchange: "XETRA", Currency: "EUR" },
];

const PA = [
  { Code: "AC",    Name: "Accor",                     Exchange: "PARIS", Currency: "EUR" },
  { Code: "AI",    Name: "Air Liquide",               Exchange: "PARIS", Currency: "EUR" },
  { Code: "AIR",   Name: "Airbus",                    Exchange: "PARIS", Currency: "EUR" },
  { Code: "MT",    Name: "ArcelorMittal",             Exchange: "PARIS", Currency: "EUR" },
  { Code: "CS",    Name: "Axa",                       Exchange: "PARIS", Currency: "EUR" },
  { Code: "BNP",   Name: "BNP Paribas",               Exchange: "PARIS", Currency: "EUR" },
  { Code: "EN",    Name: "Bouygues",                  Exchange: "PARIS", Currency: "EUR" },
  { Code: "BVI",   Name: "Bureau Veritas",            Exchange: "PARIS", Currency: "EUR" },
  { Code: "CAP",   Name: "Capgemini",                 Exchange: "PARIS", Currency: "EUR" },
  { Code: "CA",    Name: "Carrefour",                 Exchange: "PARIS", Currency: "EUR" },
  { Code: "ACA",   Name: "Credit Agricole",           Exchange: "PARIS", Currency: "EUR" },
  { Code: "BN",    Name: "Danone",                    Exchange: "PARIS", Currency: "EUR" },
  { Code: "DSY",   Name: "Dassault Systemes",         Exchange: "PARIS", Currency: "EUR" },
  { Code: "EDEN",  Name: "Edenred",                   Exchange: "PARIS", Currency: "EUR" },
  { Code: "ENGI",  Name: "Engie",                     Exchange: "PARIS", Currency: "EUR" },
  { Code: "EL",    Name: "EssilorLuxottica",          Exchange: "PARIS", Currency: "EUR" },
  { Code: "ERF",   Name: "Eurofins Scientific",       Exchange: "PARIS", Currency: "EUR" },
  { Code: "RMS",   Name: "Hermes",                    Exchange: "PARIS", Currency: "EUR" },
  { Code: "KER",   Name: "Kering",                    Exchange: "PARIS", Currency: "EUR" },
  { Code: "OR",    Name: "L'Oreal",                   Exchange: "PARIS", Currency: "EUR" },
  { Code: "LR",    Name: "Legrand",                   Exchange: "PARIS", Currency: "EUR" },
  { Code: "MC",    Name: "LVMH",                      Exchange: "PARIS", Currency: "EUR" },
  { Code: "ML",    Name: "Michelin",                  Exchange: "PARIS", Currency: "EUR" },
  { Code: "ORA",   Name: "Orange",                    Exchange: "PARIS", Currency: "EUR" },
  { Code: "RI",    Name: "Pernod Ricard",             Exchange: "PARIS", Currency: "EUR" },
  { Code: "PUB",   Name: "Publicis",                  Exchange: "PARIS", Currency: "EUR" },
  { Code: "RNO",   Name: "Renault",                   Exchange: "PARIS", Currency: "EUR" },
  { Code: "SAF",   Name: "Safran",                    Exchange: "PARIS", Currency: "EUR" },
  { Code: "SGO",   Name: "Saint-Gobain",              Exchange: "PARIS", Currency: "EUR" },
  { Code: "SAN",   Name: "Sanofi",                    Exchange: "PARIS", Currency: "EUR" },
  { Code: "SU",    Name: "Schneider Electric",        Exchange: "PARIS", Currency: "EUR" },
  { Code: "GLE",   Name: "Societe Generale",          Exchange: "PARIS", Currency: "EUR" },
  { Code: "STLAP", Name: "Stellantis",                Exchange: "PARIS", Currency: "EUR" },
  { Code: "STMPA", Name: "STMicroelectronics",        Exchange: "PARIS", Currency: "EUR" },
  { Code: "TEP",   Name: "Teleperformance",           Exchange: "PARIS", Currency: "EUR" },
  { Code: "HO",    Name: "Thales",                    Exchange: "PARIS", Currency: "EUR" },
  { Code: "TTE",   Name: "TotalEnergies",             Exchange: "PARIS", Currency: "EUR" },
  { Code: "URW",   Name: "Unibail-Rodamco-Westfield", Exchange: "PARIS", Currency: "EUR" },
  { Code: "VIE",   Name: "Veolia",                    Exchange: "PARIS", Currency: "EUR" },
  { Code: "DG",    Name: "Vinci",                     Exchange: "PARIS", Currency: "EUR" },
];

const AS = [
  { Code: "ABN",   Name: "ABN AMRO",                  Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "ADYEN", Name: "Adyen",                     Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "AGN",   Name: "Aegon",                     Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "AD",    Name: "Ahold Delhaize",            Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "AKZA",  Name: "AkzoNobel",                 Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "MT",    Name: "ArcelorMittal",             Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "ASM",   Name: "ASM International",         Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "ASML",  Name: "ASML Holding",              Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "ASRNL", Name: "ASR Nederland",             Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "BESI",  Name: "BE Semiconductor",         Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "DSFIR", Name: "DSM Firmenich",             Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "EXO",   Name: "Exor",                      Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "HEIA",  Name: "Heineken",                  Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "IMCD",  Name: "IMCD",                      Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "INGA",  Name: "ING Group",                 Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "KPN",   Name: "KPN",                       Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "NN",    Name: "NN Group",                  Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "PHIA",  Name: "Philips",                   Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "PRX",   Name: "Prosus",                    Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "RAND",  Name: "Randstad",                  Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "REN",   Name: "RELX",                      Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "SHELL", Name: "Shell plc",                 Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "UMG",   Name: "Universal Music Group",     Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "UNA",   Name: "Unilever",                  Exchange: "AMSTERDAM", Currency: "EUR" },
  { Code: "WKL",   Name: "Wolters Kluwer",            Exchange: "AMSTERDAM", Currency: "EUR" },
];

const BR = [
  { Code: "ABI",   Name: "AB InBev",                  Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "ACKB",  Name: "Ackermans & van Haaren",    Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "AED",   Name: "Aedifica",                  Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "AGS",   Name: "Ageas",                     Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "ARGX",  Name: "arGEN-X",                   Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "APAM",  Name: "Aperam",                    Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "AZE",   Name: "Azelis Group",              Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "DIE",   Name: "D'Ieteren",                 Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "ELI",   Name: "Elia Group",                Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "GBLB",  Name: "GBL",                       Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "KBC",   Name: "KBC",                       Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "LOTB",  Name: "Lotus Bakeries",            Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "MELE",  Name: "Melexis",                   Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "MONT",  Name: "Montea",                    Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "SOF",   Name: "Sofina",                    Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "SOLB",  Name: "Solvay",                    Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "SYENS", Name: "Syensqo",                   Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "UCB",   Name: "UCB",                       Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "UMI",   Name: "Umicore",                   Exchange: "BRUSSELS", Currency: "EUR" },
  { Code: "WDP",   Name: "WDP",                       Exchange: "BRUSSELS", Currency: "EUR" },
];

const LS = [
  { Code: "ALTR",  Name: "Altri",                     Exchange: "LISBON", Currency: "EUR" },
  { Code: "BCP",   Name: "Banco Comercial Portugues", Exchange: "LISBON", Currency: "EUR" },
  { Code: "COR",   Name: "Corticeira Amorim",         Exchange: "LISBON", Currency: "EUR" },
  { Code: "CTT",   Name: "CTT Correios",              Exchange: "LISBON", Currency: "EUR" },
  { Code: "EDPR",  Name: "EDP Renovaveis",            Exchange: "LISBON", Currency: "EUR" },
  { Code: "EDP",   Name: "Energias de Portugal",      Exchange: "LISBON", Currency: "EUR" },
  { Code: "GALP",  Name: "Galp Energia",              Exchange: "LISBON", Currency: "EUR" },
  { Code: "JMT",   Name: "Jeronimo Martins",          Exchange: "LISBON", Currency: "EUR" },
  { Code: "NOS",   Name: "NOS",                       Exchange: "LISBON", Currency: "EUR" },
  { Code: "RENE",  Name: "Redes Energeticas Nacionais",Exchange:"LISBON", Currency: "EUR" },
  { Code: "SEM",   Name: "Semapa",                    Exchange: "LISBON", Currency: "EUR" },
  { Code: "SON",   Name: "Sonae",                     Exchange: "LISBON", Currency: "EUR" },
  { Code: "NVG",   Name: "The Navigator Company",     Exchange: "LISBON", Currency: "EUR" },
];

const MI = [
  { Code: "A2A",   Name: "A2A",                       Exchange: "MILAN", Currency: "EUR" },
  { Code: "AMP",   Name: "Amplifon",                  Exchange: "MILAN", Currency: "EUR" },
  { Code: "AZM",   Name: "Azimut",                    Exchange: "MILAN", Currency: "EUR" },
  { Code: "BMED",  Name: "Banca Mediolanum",          Exchange: "MILAN", Currency: "EUR" },
  { Code: "BMPS",  Name: "Banca Monte dei Paschi",    Exchange: "MILAN", Currency: "EUR" },
  { Code: "BAMI",  Name: "Banco BPM",                 Exchange: "MILAN", Currency: "EUR" },
  { Code: "BPE",   Name: "BPER Banca",                Exchange: "MILAN", Currency: "EUR" },
  { Code: "BC",    Name: "Brunello Cucinelli",        Exchange: "MILAN", Currency: "EUR" },
  { Code: "BZU",   Name: "Buzzi Unicem",              Exchange: "MILAN", Currency: "EUR" },
  { Code: "CPR",   Name: "Campari",                   Exchange: "MILAN", Currency: "EUR" },
  { Code: "DIA",   Name: "Diasorin",                  Exchange: "MILAN", Currency: "EUR" },
  { Code: "ENEL",  Name: "Enel",                      Exchange: "MILAN", Currency: "EUR" },
  { Code: "ENI",   Name: "Eni",                       Exchange: "MILAN", Currency: "EUR" },
  { Code: "RACE",  Name: "Ferrari",                   Exchange: "MILAN", Currency: "EUR" },
  { Code: "FBK",   Name: "FinecoBank",                Exchange: "MILAN", Currency: "EUR" },
  { Code: "G",     Name: "Generali",                  Exchange: "MILAN", Currency: "EUR" },
  { Code: "HER",   Name: "Hera",                      Exchange: "MILAN", Currency: "EUR" },
  { Code: "ISP",   Name: "Intesa Sanpaolo",           Exchange: "MILAN", Currency: "EUR" },
  { Code: "INW",   Name: "INWIT",                     Exchange: "MILAN", Currency: "EUR" },
  { Code: "IG",    Name: "Italgas",                   Exchange: "MILAN", Currency: "EUR" },
  { Code: "LDO",   Name: "Leonardo",                  Exchange: "MILAN", Currency: "EUR" },
  { Code: "MB",    Name: "Mediobanca",                Exchange: "MILAN", Currency: "EUR" },
  { Code: "MONC",  Name: "Moncler",                   Exchange: "MILAN", Currency: "EUR" },
  { Code: "NEXI",  Name: "Nexi",                      Exchange: "MILAN", Currency: "EUR" },
  { Code: "PST",   Name: "Poste Italiane",            Exchange: "MILAN", Currency: "EUR" },
  { Code: "PRY",   Name: "Prysmian",                  Exchange: "MILAN", Currency: "EUR" },
  { Code: "REC",   Name: "Recordati",                 Exchange: "MILAN", Currency: "EUR" },
  { Code: "SPM",   Name: "Saipem",                    Exchange: "MILAN", Currency: "EUR" },
  { Code: "SRG",   Name: "Snam",                      Exchange: "MILAN", Currency: "EUR" },
  { Code: "STLAM", Name: "Stellantis",                Exchange: "MILAN", Currency: "EUR" },
  { Code: "TIT",   Name: "Telecom Italia",            Exchange: "MILAN", Currency: "EUR" },
  { Code: "TEN",   Name: "Tenaris",                   Exchange: "MILAN", Currency: "EUR" },
  { Code: "TRN",   Name: "Terna",                     Exchange: "MILAN", Currency: "EUR" },
  { Code: "UCG",   Name: "UniCredit",                 Exchange: "MILAN", Currency: "EUR" },
  { Code: "UNI",   Name: "Unipol",                    Exchange: "MILAN", Currency: "EUR" },
];

const SW = [
  { Code: "NESN",  Name: "Nestle",                    Exchange: "SIX", Currency: "CHF" },
  { Code: "ROG",   Name: "Roche Holding",             Exchange: "SIX", Currency: "CHF" },
  { Code: "NOVN",  Name: "Novartis",                  Exchange: "SIX", Currency: "CHF" },
  { Code: "CFR",   Name: "Richemont",                 Exchange: "SIX", Currency: "CHF" },
  { Code: "ZURN",  Name: "Zurich Insurance",          Exchange: "SIX", Currency: "CHF" },
  { Code: "UBSG",  Name: "UBS Group",                 Exchange: "SIX", Currency: "CHF" },
  { Code: "ABBN",  Name: "ABB",                       Exchange: "SIX", Currency: "CHF" },
  { Code: "LONN",  Name: "Lonza Group",               Exchange: "SIX", Currency: "CHF" },
  { Code: "SIKA",  Name: "Sika",                      Exchange: "SIX", Currency: "CHF" },
  { Code: "ALC",   Name: "Alcon",                     Exchange: "SIX", Currency: "CHF" },
  { Code: "GIVN",  Name: "Givaudan",                  Exchange: "SIX", Currency: "CHF" },
  { Code: "HOLN",  Name: "Holcim",                    Exchange: "SIX", Currency: "CHF" },
  { Code: "SCMN",  Name: "Swisscom",                  Exchange: "SIX", Currency: "CHF" },
  { Code: "PGHN",  Name: "Partners Group",            Exchange: "SIX", Currency: "CHF" },
  { Code: "SREN",  Name: "Swiss Re",                  Exchange: "SIX", Currency: "CHF" },
  { Code: "SOON",  Name: "Sonova",                    Exchange: "SIX", Currency: "CHF" },
  { Code: "GEBN",  Name: "Geberit",                   Exchange: "SIX", Currency: "CHF" },
  { Code: "SLHN",  Name: "Swiss Life",                Exchange: "SIX", Currency: "CHF" },
  { Code: "LOGN",  Name: "Logitech",                  Exchange: "SIX", Currency: "CHF" },
  { Code: "KNIN",  Name: "Kuehne Nagel",              Exchange: "SIX", Currency: "CHF" },
];

const LSE = [
  { Code: "III",   Name: "3i",                        Exchange: "LSE", Currency: "GBP" },
  { Code: "ADM",   Name: "Admiral Group",             Exchange: "LSE", Currency: "GBP" },
  { Code: "AAL",   Name: "Anglo American",            Exchange: "LSE", Currency: "GBP" },
  { Code: "ANTO",  Name: "Antofagasta",               Exchange: "LSE", Currency: "GBP" },
  { Code: "ABF",   Name: "Associated British Foods",  Exchange: "LSE", Currency: "GBP" },
  { Code: "AZN",   Name: "AstraZeneca",               Exchange: "LSE", Currency: "GBP" },
  { Code: "AUTO",  Name: "Autotrader Group",          Exchange: "LSE", Currency: "GBP" },
  { Code: "AV",    Name: "Aviva",                     Exchange: "LSE", Currency: "GBP" },
  { Code: "BA",    Name: "BAE Systems",               Exchange: "LSE", Currency: "GBP" },
  { Code: "BARC",  Name: "Barclays",                  Exchange: "LSE", Currency: "GBP" },
  { Code: "BTRW",  Name: "Barratt Redrow",            Exchange: "LSE", Currency: "GBP" },
  { Code: "BKG",   Name: "Berkeley Group",            Exchange: "LSE", Currency: "GBP" },
  { Code: "BP",    Name: "BP",                        Exchange: "LSE", Currency: "GBP" },
  { Code: "BATS",  Name: "British American Tobacco",  Exchange: "LSE", Currency: "GBP" },
  { Code: "BLND",  Name: "British Land",              Exchange: "LSE", Currency: "GBP" },
  { Code: "BT",    Name: "BT Group",                  Exchange: "LSE", Currency: "GBP" },
  { Code: "BNZL",  Name: "Bunzl",                     Exchange: "LSE", Currency: "GBP" },
  { Code: "BRBY",  Name: "Burberry Group",            Exchange: "LSE", Currency: "GBP" },
  { Code: "CNA",   Name: "Centrica",                  Exchange: "LSE", Currency: "GBP" },
  { Code: "CCEP",  Name: "Coca-Cola Europacific",     Exchange: "LSE", Currency: "GBP" },
  { Code: "CPG",   Name: "Compass Group",             Exchange: "LSE", Currency: "GBP" },
  { Code: "CRDA",  Name: "Croda International",       Exchange: "LSE", Currency: "GBP" },
  { Code: "DGE",   Name: "Diageo",                    Exchange: "LSE", Currency: "GBP" },
  { Code: "DPLM",  Name: "Diploma",                   Exchange: "LSE", Currency: "GBP" },
  { Code: "EXPN",  Name: "Experian",                  Exchange: "LSE", Currency: "GBP" },
  { Code: "FRES",  Name: "Fresnillo",                 Exchange: "LSE", Currency: "GBP" },
  { Code: "GAW",   Name: "Games Workshop",            Exchange: "LSE", Currency: "GBP" },
  { Code: "GLEN",  Name: "Glencore",                  Exchange: "LSE", Currency: "GBP" },
  { Code: "GSK",   Name: "GSK",                       Exchange: "LSE", Currency: "GBP" },
  { Code: "HLN",   Name: "Haleon",                    Exchange: "LSE", Currency: "GBP" },
  { Code: "HLMA",  Name: "Halma",                     Exchange: "LSE", Currency: "GBP" },
  { Code: "HWDN",  Name: "Howdens Joinery",           Exchange: "LSE", Currency: "GBP" },
  { Code: "HSBA",  Name: "HSBC",                      Exchange: "LSE", Currency: "GBP" },
  { Code: "IHG",   Name: "IHG Hotels & Resorts",      Exchange: "LSE", Currency: "GBP" },
  { Code: "IMI",   Name: "IMI",                       Exchange: "LSE", Currency: "GBP" },
  { Code: "IMB",   Name: "Imperial Brands",           Exchange: "LSE", Currency: "GBP" },
  { Code: "INF",   Name: "Informa",                   Exchange: "LSE", Currency: "GBP" },
  { Code: "IAG",   Name: "International Airlines Group",Exchange:"LSE", Currency: "GBP" },
  { Code: "ITRK",  Name: "Intertek",                  Exchange: "LSE", Currency: "GBP" },
  { Code: "JD",    Name: "JD Sports",                 Exchange: "LSE", Currency: "GBP" },
  { Code: "KGF",   Name: "Kingfisher",                Exchange: "LSE", Currency: "GBP" },
  { Code: "LAND",  Name: "Land Securities",           Exchange: "LSE", Currency: "GBP" },
  { Code: "LGEN",  Name: "Legal & General",           Exchange: "LSE", Currency: "GBP" },
  { Code: "LLOY",  Name: "Lloyds Banking Group",      Exchange: "LSE", Currency: "GBP" },
  { Code: "LSEG",  Name: "London Stock Exchange Group",Exchange:"LSE", Currency: "GBP" },
  { Code: "MNG",   Name: "M&G",                       Exchange: "LSE", Currency: "GBP" },
  { Code: "MKS",   Name: "Marks & Spencer",           Exchange: "LSE", Currency: "GBP" },
  { Code: "MRO",   Name: "Melrose Industries",        Exchange: "LSE", Currency: "GBP" },
  { Code: "MNDI",  Name: "Mondi",                     Exchange: "LSE", Currency: "GBP" },
  { Code: "NG",    Name: "National Grid",             Exchange: "LSE", Currency: "GBP" },
  { Code: "NWG",   Name: "NatWest Group",             Exchange: "LSE", Currency: "GBP" },
  { Code: "NXT",   Name: "Next",                      Exchange: "LSE", Currency: "GBP" },
  { Code: "PSON",  Name: "Pearson",                   Exchange: "LSE", Currency: "GBP" },
  { Code: "PSN",   Name: "Persimmon",                 Exchange: "LSE", Currency: "GBP" },
  { Code: "PRU",   Name: "Prudential",                Exchange: "LSE", Currency: "GBP" },
  { Code: "RKT",   Name: "Reckitt",                   Exchange: "LSE", Currency: "GBP" },
  { Code: "REL",   Name: "RELX",                      Exchange: "LSE", Currency: "GBP" },
  { Code: "RTO",   Name: "Rentokil Initial",          Exchange: "LSE", Currency: "GBP" },
  { Code: "RMV",   Name: "Rightmove",                 Exchange: "LSE", Currency: "GBP" },
  { Code: "RIO",   Name: "Rio Tinto",                 Exchange: "LSE", Currency: "GBP" },
  { Code: "RR",    Name: "Rolls-Royce",               Exchange: "LSE", Currency: "GBP" },
  { Code: "SGE",   Name: "Sage Group",                Exchange: "LSE", Currency: "GBP" },
  { Code: "SBRY",  Name: "Sainsbury's",               Exchange: "LSE", Currency: "GBP" },
  { Code: "SMT",   Name: "Scottish Mortgage IT",      Exchange: "LSE", Currency: "GBP" },
  { Code: "SGRO",  Name: "Segro",                     Exchange: "LSE", Currency: "GBP" },
  { Code: "SVT",   Name: "Severn Trent",              Exchange: "LSE", Currency: "GBP" },
  { Code: "SHEL",  Name: "Shell",                     Exchange: "LSE", Currency: "GBP" },
  { Code: "SMIN",  Name: "Smiths Group",              Exchange: "LSE", Currency: "GBP" },
  { Code: "SN",    Name: "Smith & Nephew",            Exchange: "LSE", Currency: "GBP" },
  { Code: "SPX",   Name: "Spirax Group",              Exchange: "LSE", Currency: "GBP" },
  { Code: "SSE",   Name: "SSE",                       Exchange: "LSE", Currency: "GBP" },
  { Code: "STAN",  Name: "Standard Chartered",        Exchange: "LSE", Currency: "GBP" },
  { Code: "TSCO",  Name: "Tesco",                     Exchange: "LSE", Currency: "GBP" },
  { Code: "ULVR",  Name: "Unilever",                  Exchange: "LSE", Currency: "GBP" },
  { Code: "UU",    Name: "United Utilities",          Exchange: "LSE", Currency: "GBP" },
  { Code: "VOD",   Name: "Vodafone",                  Exchange: "LSE", Currency: "GBP" },
  { Code: "WEIR",  Name: "Weir Group",                Exchange: "LSE", Currency: "GBP" },
  { Code: "WTB",   Name: "Whitbread",                 Exchange: "LSE", Currency: "GBP" },
];

const TYPE = "COMMON STOCK";

function addType(assets) {
  return assets.map(a => ({ ...a, Type: TYPE, Status: "active" }));
}

export const STATIC_ASSETS_BY_EXCHANGE = {
  US:    addType(US),
  XETRA: addType(XETRA),
  PA:    addType(PA),
  AS:    addType(AS),
  BR:    addType(BR),
  LS:    addType(LS),
  MI:    addType(MI),
  SW:    addType(SW),
  LSE:   addType(LSE),
};

export function getStaticAssetsForExchange(providerExchange) {
  return STATIC_ASSETS_BY_EXCHANGE[providerExchange] ?? [];
}

export const STATIC_TOTAL_COUNT = Object.values(STATIC_ASSETS_BY_EXCHANGE)
  .reduce((sum, arr) => sum + arr.length, 0);
