import { addTop8CostPolicyMetadata } from "./_lib/top8CostPolicy.js";
import { runControlledTop8Pipeline } from "./_lib/top8Pipeline.js";
import { buildUniverseResponse } from "./universe.js";

const APP_NAME = "EMRR 2.0 / Tendencias";
const PHASE = "6";
const UNIVERSE_MODE = "DYNAMIC_UNIVERSE";
const MAX_OUTPUT_ASSETS = 8;

function sendJson(response, statusCode, payload) {
  if (response && typeof response.status === "function") {
    return response.status(statusCode).json(payload);
  }

  if (response && typeof response.writeHead === "function") {
    response.writeHead(statusCode, { "content-type": "application/json; charset=utf-8" });
    response.end(JSON.stringify(payload));
    return undefined;
  }

  return new Response(JSON.stringify(payload), {
    status: statusCode,
    headers: { "content-type": "application/json; charset=utf-8" },
  });
}

function hasQuery(request) {
  return Boolean(request.query && Object.keys(request.query).length > 0);
}

export default async function handler(request, response) {
  if (request.method && request.method !== "GET") {
    return sendJson(response, 405, {
      ok: false,
      error: "METHOD_NOT_ALLOWED",
      message: "Only GET is allowed for the controlled TOP 8 endpoint.",
    });
  }

  if (hasQuery(request)) {
    return sendJson(response, 400, {
      ok: false,
      error: "QUERY_NOT_ALLOWED",
      message: "Phase 6 TOP 8 does not accept ad hoc tickers, custom lists or custom exchanges.",
    });
  }

  const timestampUtc = new Date().toISOString();
  const universe = await buildUniverseResponse({ includeFullAssets: true });

  if (!universe.ok) {
    return sendJson(response, 409, {
      ok: false,
      app: APP_NAME,
      phase: PHASE,
      mode: universe.mode,
      universeMode: UNIVERSE_MODE,
      timestampUtc,
      error: "UNIVERSE_DISCOVERY_NOT_READY",
      universeSummary: universe.summary,
      blockedReasons: [universe.error ?? "UNIVERSE_DISCOVERY_FAILED"],
      warnings: universe.warnings ?? [],
      assets: [],
      message: "TOP 8 cannot run until automatic universe discovery returns candidates.",
    });
  }

  const pipeline = await runControlledTop8Pipeline({
    assets: universe.assets,
    marketStatus: "UNKNOWN",
    dataQuality: "GOOD",
  });

  if (!pipeline.ok) {
    return sendJson(response, 409, addTop8CostPolicyMetadata({
      ok: false,
      app: APP_NAME,
      phase: PHASE,
      mode: "CONTROLLED_REAL_DATA",
      universeMode: UNIVERSE_MODE,
      timestampUtc,
      error: pipeline.error,
      universeSummary: universe.summary,
      evaluationSummary: pipeline.summary,
      costGate: pipeline.costGate,
      batchPlan: pipeline.batchPlan,
      providerCallsPlanned: pipeline.providerCallsPlanned,
      maxOutputAssets: MAX_OUTPUT_ASSETS,
      blockedReasons: [pipeline.error],
      warnings: [
        "No fixed manual ticker universe is used.",
        "TOP 8 remains blocked when the automatic universe exceeds the manual cost gate.",
        "No scanner, polling, auto-refresh, background job, database write or order routing is active.",
      ],
      assets: [],
      message:
        "Controlled TOP 8 pipeline is wired, but calculation is blocked until the automatic universe can be processed within the approved cost gate.",
    }, {
      batchPlan: pipeline.batchPlan,
      dryRun: false,
      fullUniverseRequested: true,
      providerCallsPlanned: pipeline.providerCallsPlanned,
      blockedReasons: [pipeline.error],
    }));
  }

  return sendJson(response, 200, addTop8CostPolicyMetadata({
    ok: true,
    app: APP_NAME,
    phase: PHASE,
    mode: "CONTROLLED_REAL_DATA",
    universeMode: UNIVERSE_MODE,
    timestampUtc,
    universeSummary: universe.summary,
    evaluationSummary: pipeline.summary,
    costGate: pipeline.costGate,
    providerCallsPlanned: pipeline.providerCallsPlanned,
    maxOutputAssets: MAX_OUTPUT_ASSETS,
    warnings: [
      "No EXEC is generated by Phase 6.",
      "Market status remains conservative unless a verified OPEN state is provided.",
    ],
    assets: pipeline.assets,
  }, {
    batchPlan: pipeline.batchPlan,
    dryRun: false,
    fullUniverseRequested: true,
    providerCallsPlanned: pipeline.providerCallsPlanned,
  }));
}
